package app.n_zik.compagnon.about

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import java.util.logging.Logger
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.decodeFromJsonElement

/**
 * The embedded contributors (spec `spec-updater` AD-10 — port of the phone's
 * `extensions/contributors/Contributors.kt`, its Gson swapped for kotlinx.serialization, its
 * `R.raw.*` reads swapped for JVM classpath resources): the contributors ride IN the app (no
 * network fetch — the phone convention). The files sit in `app/src/main/resources/` (this
 * Compose Multiplatform version's resource pipeline has no `raw` type — the desktop equivalent of
 * the phone's `res/raw`). The pure [parseDevelopers] /
 * [parseTranslators] are pinned by `ContributorsTest`; the one-shot init reads the resource, and a
 * parse failure logs and yields `emptyList()` (the phone's behaviour — the section simply stays
 * empty).
 *
 * Sorts (the phone's): developers by `login` ([Developer.username]), translators by
 * `displayName` (falling back to the username when the display name is absent — the phone's
 * nullable sort would have crashed on a null; the embedded data has none).
 *
 * Provenance (this repo's own CI, verified): `contributors.json` is this repo's own
 * contributors list, regenerated by the `weekly-update-contributors.yaml` workflow (weekly,
 * Saturday 23:00 — `.github/get_developers.py` against the GitHub API, auto-committed to
 * `app/src/main/resources/`); `translators.json` is the Crowdin dynamic list, regenerated by
 * the `weekly-update-translators.yaml` workflow (same schedule — `.github/get_translators.py`
 * against Crowdin, through the workflow's secrets). Both are committed static data embedded in
 * the app (no runtime fetch — the phone's About-page convention).
 */
object Contributors {

    private val log = Logger.getLogger("Contributors")

    private val json = Json {
        ignoreUnknownKeys = true
    }

    /**
     * Parses a `contributors.json` payload (PURE — the phone's `initDevelopers` de-Androided):
     * the list sorted by `login`; ANY failure → `emptyList()` (the phone's catch).
     */
    fun parseDevelopers(payload: String): List<Developer> = try {
        json.decodeFromString<JsonArray>(payload)
            .map { json.decodeFromJsonElement<Developer>(it) }
            .sortedBy { it.username }
    } catch (e: Exception) {
        log.warning("parseDevelopers failed: ${e::class.simpleName} (${e.message})")
        emptyList()
    }

    /** Parses a `translators.json` payload (PURE): the list sorted by display name; any failure → `emptyList()`. */
    fun parseTranslators(payload: String): List<Translator> = try {
        json.decodeFromString<JsonArray>(payload)
            .map { json.decodeFromJsonElement<Translator>(it) }
            .sortedBy { it.displayName ?: it.username }
    } catch (e: Exception) {
        log.warning("parseTranslators failed: ${e::class.simpleName} (${e.message})")
        emptyList()
    }

    @Volatile
    private var developers: List<Developer>? = null

    @Volatile
    private var translators: List<Translator>? = null

    /** Reads the embedded classpath resource [name] as text (the phone's `R.raw` equivalent). */
    private fun readResource(name: String): String =
        (Contributors::class.java.getResourceAsStream("/$name") ?: error("embedded $name is missing"))
            .bufferedReader().use { it.readText() }

    /** The developers, read once from the embedded `contributors.json` (the phone's `developersList`). */
    fun developers(): List<Developer> = developers
        ?: synchronized(this) {
            developers
                ?: runCatching { parseDevelopers(readResource("contributors.json")) }
                    .onFailure { log.warning("contributors.json unreadable: ${it.message}") }
                    .getOrDefault(emptyList())
                    .also { developers = it }
        }

    /** The translators, read once from the embedded `translators.json` (the phone's `translatorsList`). */
    fun translators(): List<Translator> = translators
        ?: synchronized(this) {
            translators
                ?: runCatching { parseTranslators(readResource("translators.json")) }
                    .onFailure { log.warning("translators.json unreadable: ${it.message}") }
                    .getOrDefault(emptyList())
                    .also { translators = it }
        }

    /** The phone's `countDevelopers()`. */
    @Composable
    fun countDevelopers(): Int = developers().size

    /** The phone's `countTranslators()`. */
    @Composable
    fun countTranslators(): Int = translators().size

    /**
     * The developers' cards (the phone's `ShowDevelopers`): the 600 dp scrolling list, empty when
     * the embedded list could not be read.
     */
    @Composable
    fun ShowDevelopers() {
        val list = developers()
        if (list.isEmpty()) return

        Box(Modifier.fillMaxWidth().height(600.dp)) {
            LazyColumn(Modifier.fillMaxWidth().padding(top = 15.dp)) {
                items(list) { it.let { d -> DeveloperCard(d) } }
            }
        }
    }

    /** The translators' cards (the phone's `ShowTranslators`). */
    @Composable
    fun ShowTranslators() {
        val list = translators()
        if (list.isEmpty()) return

        Box(Modifier.fillMaxWidth().height(600.dp)) {
            LazyColumn(Modifier.fillMaxWidth().padding(top = 15.dp)) {
                items(list) { it.let { t -> TranslatorCard(t) } }
            }
        }
    }
}
