package app.n_zik.compagnon.about

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.File

/**
 * The embedded contributors (spec `spec-updater` AD-10): the pure [Contributors.parseDevelopers] /
 * [Contributors.parseTranslators] loaders against the REAL embedded JSON (committed under
 * `app/src/main/resources/` — the desktop equivalent of the phone's `R.raw`: `contributors.json`
 * is the DESKTOP repo's own contributor list (GitHub), `translators.json` is the N-Zik Crowdin
 * project's contributor list (generated by `.github/get_translators.py` — the same script the
 * phone's weekly workflow runs), and the [AboutLinks] URL construction (the DESKTOP repo +
 * the phone's issue-template paths).
 *
 * The test working dir is the `app` module dir (Gradle JVM tests), so the files are read by
 * their module-relative path.
 */
class ContributorsTest {

    private val contributorsJson = File("src/main/resources/contributors.json")
    private val translatorsJson = File("src/main/resources/translators.json")

    @Test
    fun `the embedded developers parse from the real file`() {
        assertTrue(contributorsJson.isFile, "contributors.json is missing from the module")
        val developers = Contributors.parseDevelopers(contributorsJson.readText())
        // The embedded file: the desktop repo's 2 contributors
        assertEquals(2, developers.size)
        // Sorted by `login` (the GitHub username)
        assertEquals(developers.map { it.username }.sorted(), developers.map { it.username })
    }

    @Test
    fun `the embedded developers carry the phone fields`() {
        val developers = Contributors.parseDevelopers(contributorsJson.readText())
        // The first entry of the embedded file: NEVERLeVrai (id 63956787, 408 contributions —
        // re-pinned when the contributors.json refresh workflow updates the list)
        val first = developers.first { it.username == "NEVARLeVrai" }
        assertEquals(63956787, first.id)
        assertEquals(408, first.contributions)
        assertTrue(first.url.startsWith("https://github.com/"))
        assertTrue(first.avatar.startsWith("https://avatars.githubusercontent.com/"))
        // The embedded data has no GitHub `name` field: the display name falls back to the login
        assertEquals(null, first.displayName)
    }

    @Test
    fun `the embedded bot entry parses with its handle from the apps url`() {
        // The desktop list's bot: the bracketed `login` and the `apps/` profile URL (the
        // `handle` is the URL's last segment, so the card shows @dependabot, not @dependabot[bot])
        val developers = Contributors.parseDevelopers(contributorsJson.readText())
        val bot = developers.first { it.username == "dependabot[bot]" }
        assertEquals(49699333, bot.id)
        assertEquals(3, bot.contributions)
        assertEquals("https://github.com/apps/dependabot", bot.url)
        assertEquals("dependabot", bot.handle)
    }

    @Test
    fun `the embedded translators parse from the real file`() {
        assertTrue(translatorsJson.isFile, "translators.json is missing from the module")
        val translators = Contributors.parseTranslators(translatorsJson.readText())
        // The embedded file: the N-Zik Crowdin project's 10 contributors (re-pinned when the
        // weekly `get_translators.py` workflow refreshes the list)
        assertEquals(10, translators.size)
        // Sorted by display name
        assertEquals(
            translators.map { it.displayName ?: it.username }.sorted(),
            translators.map { it.displayName ?: it.username },
        )
        // Every entry carries a display name (the embedded data has no nulls)
        assertTrue(translators.all { it.displayName != null })
    }

    @Test
    fun `the owner entry carries the crowdin profile and the bulk-imported languages`() {
        // The N-Zik project owner's bulk imports translated every target language — the entry's
        // profile is the Crowdin one (the old fast4x entry belonged to the retired upstream
        // bootstrap list, which is what the dynamic Crowdin list replaces)
        val translators = Contributors.parseTranslators(translatorsJson.readText())
        val owner = translators.first { it.username == "NEVARLeVrai" }
        assertEquals("NΞVΛR", owner.displayName)
        assertTrue(owner.languages.contains("French"))
        assertTrue(owner.languages.contains("German"))
        assertTrue(owner.languages.contains("Italian"))
        assertTrue(owner.languages.contains("Turkish"))
        assertEquals("https://crowdin.com/profile/NEVARLeVrai", owner.profileUrl)
        assertTrue((owner.avatarUrl ?: "").startsWith("https://crowdin-static."))
    }

    @Test
    fun `a corrupt payload yields an empty list without throwing`() {
        // The phone's behaviour: a read/parse failure logs and the section stays empty
        assertTrue(Contributors.parseDevelopers("not a json array").isEmpty())
        assertTrue(Contributors.parseTranslators("{ broken: ").isEmpty())
        assertTrue(Contributors.parseDevelopers("").isEmpty())
        assertTrue(Contributors.parseTranslators("[]").isEmpty())
    }

    @Test
    fun `the about links point at the desktop repo`() {
        assertEquals("https://github.com/N-Zik-Group/N-Zik-Desktop-Compagnon", AboutLinks.DESKTOP_REPO_URL)
        assertEquals("https://github.com/N-Zik-Group", AboutLinks.REPO_OWNER_URL)
        // The phone's issue-template paths, on the DESKTOP repo
        assertEquals(
            "https://github.com/N-Zik-Group/N-Zik-Desktop-Compagnon/issues/new?assignees=&labels=bug&template=bug_report.yaml",
            AboutLinks.issueUrl("bug"),
        )
        assertEquals(
            "https://github.com/N-Zik-Group/N-Zik-Desktop-Compagnon/issues/new?assignees=&labels=feature_request&template=feature_request.yaml",
            AboutLinks.issueUrl("feature"),
        )
    }
}
